import { food } from "./app/shared/models/food";
import { Tag } from "./app/shared/models/tag";





export const sample_foods: food[] = [
  {
    id:'1',
    name: 'Pizza Pepperoni',
    cookTime: '10-20',
    price: 499,
    favorite: false,
    origins: ['italy'],
    starts: 4.5,
    imageUrl: 'image/food-1.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'2',
    name: 'Meatball',
    price: 349,
    cookTime: '20-30',
    favorite: true,
    origins: [ 'middle east'],
    starts: 4.7,
    imageUrl: 'image/food-2.jpg',
    tags: ['SlowFood', 'Lunch'],
  },
  {
    id:'3',
    name: 'Hamburger',
    price: 299,
    cookTime: '10-15',
    favorite: false,
    origins: ['germany', 'us'],
    starts: 3.5,
    imageUrl: 'image/food-3.jpg',
    tags: ['FastFood', 'Hamburger'],
  },
  {
    id:'4',
    name: 'Fried Potatoes',
    price: 199,
    cookTime: '15-20',
    favorite: true,
    origins: ['belgium', 'france'],
    starts: 3.3,
    imageUrl: 'image/food-4.jpg',
    tags: ['FastFood', 'Fry'],
  },
  {
    id:'5',
    name: 'Chicken Soup',
    price: 399,
    cookTime: '40-50',
    favorite: false,
    origins: ['india', 'asia'],
    starts: 3.0,
    imageUrl: 'image/food-5.jpg',
    tags: ['SlowFood', 'Soup'],
  },
  {
    id:'6',
    name: 'Vegetables Pizza',
    price: 467,
    cookTime: '40-50',
    favorite: false,
    origins: ['italy'],
    starts: 4.0,
    imageUrl: 'image/food-6.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
  {
    id:'7',
    name: 'Spicy Cheese Burger',
    price: 399,
    cookTime: '20-30',
    favorite: false,
    origins: ['Indian'],
    starts: 4.0,
    imageUrl: 'image/food-7.jpg',
    tags: ['FastFood', 'Burger', 'Lunch'],
  },
  {
    id:'8',
    name: 'Vegetables Magento Pizza',
    price: 499,
    cookTime: '45-50',
    favorite: false,
    origins: ['indian'],
    starts: 4.0,
    imageUrl: 'image/food-8.jpg',
    tags: ['FastFood', 'Pizza', 'Lunch'],
  },
]
export const sample_tags:Tag[] = [
  { name: 'All', count: 8 },
  { name: 'FastFood', count: 4 },
  { name: 'Pizza', count: 3 },
  { name: 'Lunch', count: 3 },
  { name: 'SlowFood', count: 2 },
  { name: 'Hamburger', count: 2 },
  { name: 'Fry', count: 1 },
  { name: 'Soup', count: 1 },
]

